### ISSUE TITLE
Rename to blinkkcode/degu

### ISSUE THREAD

**Issue by jeremydw** [blinkkcode/degu#56]
Filing an issue to track renaming the project to Degu. Note that we won't change anything about our current release, so projects that depend on npm package Yano can continue to do so and won't break.

1. Move to `blinkkcode/degu` on GitHub, with package `@blinkk/degu`.
2. Set up GitHub Actions to publish whenever `package.json`'s version changes (see example from https://github.com/blinkkcode/fileset/blob/main/.github/workflows/publish.yml)
3. Audit docs and change references/branding as needed
4. Update project dependencies
5. Get a mascot illustrated :)

Thoughts @uxder @angusm @stevenle ?

**Comment by uxder** [comment]
Sounds good to me 👍

**Comment by jeremydw** [comment]
All bits other than 4 and 5 are complete now.

**Comment by stevenle** [comment]
Let's close this out. Mascot can be handled in a separate issue.
