### ISSUE TITLE
CssVarInterpolate should automatically set `visibility: hidden` for opacity: 0

### ISSUE THREAD

**Issue by uxder** [blinkkcode/degu#65]
Brainstorming ways for cssVarInterpolate to automatically set `visibility: hidden` when opacity is set to 0.

Key issues:
1) cssVarInterpolate is element agnostic.  It ONLY creates css variables.  It is up to the user to add and use the variable in css.
2) the variables names are up to the user.  Therefore, there is no definitive way to know if this particular css variable is going to be used for opacity.

```
 {
            progress: [{ from: 0, to: 0.3, start: 0, end: 1 },],
            id: '--hohoho'
 },
         
.myvar
    opacity: var(--hohoho)
```

### 1 - assume the name `opacity` in the css variable.

If the word opacity is found in the css variable, cssvarinterpolate will automatically create a visibility variable for you.  
```
 {
            progress: [{ from: 0, to: 0.3, start: 0, end: 1 },],
            id: '--my-opacity'
 },
         
.myvar
    opacity: var(--my-opacity)
    visibility: var(--my-visibility)
```

### 2 - Add a flag for visibility var.

If the word opacity is found in the css variable, cssvarinterpolate will automatically create a visibility variable for you.  
```
 {
            progress: [{ from: 0, to: 0.3, start: 0, end: 1 },],
            id: '--my-opacity'
            generateVisibilityVarAs: '--my-visibility'
 },
         
.myvar
    opacity: var(--my-opacity)
    visibility: var(--my-visibility)
```

### 3 - Opacity mutationobserver
Since cssVarInterpolate was never designed to directly manipulate elements, we could have a new class that observes opacity and sets visibility: hidden.  However, this might be an expensive operation.

**Comment by jeremydw** [comment]
Option 2 looks best to me, but I suggest it not being magical by detecting for the "opacity" word.

Maybe just do this:

1. Name it `visibilityId: '--my-visibility'`. The reasoning behind the name is... that is consistent with the `id` key but is special and manages the `visibility` property values only.
2. When `visibilityId` is enabled, assume that when start is "0" the value should be "hidden". When start > 0 it's "visible".

How does that sound?

**Comment by uxder** [comment]
Sounds good - I'll work on these upgrades.
